---
- name: Example Playbook to apply cis_ubuntu_2004 role with ipv6.
  hosts: localhost  # or any grouping of hosts
  connection: local  # or 'ssh'
  become: yes
  gather_facts: true
  roles:
    - cis_ubuntu_2004
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ubuntu_2004_cis_require_ipv6: true

    # DISABLE 1.1.1.6 as it results with error | modprobe: FATAL: Module squashfs is builtin.
    ubuntu_2004_cis_section1_rule_1_1_1_6: false
